### ISSUE TITLE
Custom Highlight Colours

### ISSUE THREAD

**Issue by interface-master** [expandjs/mat-elements#2]
I am unable to change the highlight colour of mat-text-field - the text and underline that come up are always blue - no matter how I try to change it through CSS or attribute tags.
Is there something I'm missing?

**Comment by Pupix** [comment]
Hello!

Currently the only way to change the highlight color is by using ::shadow selectors. An update will come in the following days implementing CSS variables which will let you overwrite the default colors without the need to use shadow piercing selectors.

Cheers.

**Comment by interface-master** [comment]
Cool. Thanks for the prompt reply.
Is there documentation on how to do that, or do I just need to poke around until it works?

**Comment by Pupix** [comment]
If you don't want to poke around you can check out [this example](http://expandjs.com/samples/youtube) where you can find a `mat-text-field` with a white highlight color by clicking on the `search icon`. In the [source code](http://expandjs.com/sources/youtube.html) the `mat-text-field` is on line 187 and its style is on line 65.

**Comment by interface-master** [comment]
You're amazing.
Thank you!! :-)

**Comment by Pupix** [comment]
With the latest release we've added the CSS variable `--mat-focused-color` on all inputs. As the name suggests, when an input is focused the color from the variable will be applied, if the variable is not defined a default color will be applied.

**Comment by interface-master** [comment]
Perfect. Thanks again!
