### ISSUE TITLE
Radio Buttons

### ISSUE THREAD

**Issue by interface-master** [expandjs/mat-elements#3]
Is there a plan in the near future to implement radio buttons?
(i'm currently faking the functionality with checkboxes, but I feel like the interface might not be intuitive to the user)

**Comment by Pupix** [comment]
Yes, radio buttons should be available pretty soon.

**Comment by Pupix** [comment]
You can find radio buttons in the form of `mat-radio` [here](http://expandjs.com/elements/mat-radio)

**Comment by interface-master** [comment]
Fantastic. Thanks so much!
